### ISSUE TITLE
[flawhud] Custom backgrounds do not apply

### ISSUE THREAD

**Issue by Firerr** [CriticalFlaw/TF2HUD.Editor#234]
Custom Backgrounds applied from TF2 Hud Editor, do not apply and default to the backgrounds in \materials\console. My 1920x1080 wallpapers were working previously before I updated the hud schema. I have tried with different wallpapers of the same resolution and from a fresh install of the hud, with no luck.

**Comment by CriticalFlaw** [comment]
Can you post a screenshot of your editor page please? The broken mode selection was fixed a while ago so you may be missing the latest flawhud schema in the editor.

**Comment by CriticalFlaw** [comment]
Retested with the latest editor and HUD version. The custom background applies correctly, so does the "Old Mode Selection".

"Main Menu Class Images" toggle that would hide the grill also works and will be renamed to "Hide Menu Images" shortly.

The default background toggle would not work because you are overriding it with a custom background which will persist across the entire HUD. If you want to have default backgrounds, you need to remove the custom background and reinstall the HUD as instructed by the prompt that shows up when you try to set a custom background.

![20240817164941_1](https://github.com/user-attachments/assets/8e1b2eb5-b520-48a8-9417-5656dcac4eea)

![20240817165001_1](https://github.com/user-attachments/assets/9b6e457e-0418-42e1-bbde-841cca900f9c)

**Comment by CriticalFlaw** [comment]
@Firerr please see comment above and let me know if there's are still any issues. Thanks.

**Comment by Firerr** [comment]
So I disabled main menu class images (I didn't consider grill to be part of the category), cleared my custom background image. I then reinstalled the program and hud, and re added my custom background. A new schema update did appear, which I applied.
![Screenshot_293](https://github.com/user-attachments/assets/e8f9cb99-f443-4f9b-b246-792922994652)

Ok yeah still getting issues, my tf2 is looking nothing like your own screenshots, the custom background does appear while launching the game, but is being overriden by full moon, quickplay core and arena are missing. Another issue has arisen, hud elements are bugged out.
![Screenshot_292](https://github.com/user-attachments/assets/2442b4c1-3139-438a-b5ac-5b509c1c0d51)
![Screenshot_290](https://github.com/user-attachments/assets/cb0256b3-e189-4972-80bd-014e9f1d86c9)

**Comment by Firerr** [comment]
![Screenshot_294](https://github.com/user-attachments/assets/8dbc23d7-ba0f-4ed3-867b-59d9f303a3ae)
this is what i get if i have the hud already installed and then reinstall the hud program, and apply the new hud schema(following the steps in the previous comment)

**Comment by CriticalFlaw** [comment]
Can you try downloading and placing the below file into your editor's JSON folder please?

Download: [flawhud.json](https://github.com/user-attachments/files/16654309/flawhud.json)

You're on the correct version of the HUD at least so the remaining issues are due to an outdated schema. Not sure why the editor is not pulling the latest version for you. The above file is what I have on my end so hopefully it resolves the issue. You won't need to reinstall the editor, only the HUD just to be safe.

**Comment by Firerr** [comment]
it fixes the issues with the hud elements but old loadout and the background are still not showing, trying to set a new background is actually just crashing the hud editor

**Comment by Firerr** [comment]
ok ive managed to fix it myself, to get it to work i had first nuke the appdata files related to tf2-hud-editor, then like magic everything started working.

**Comment by CriticalFlaw** [comment]
> ok ive managed to fix it myself, to get it to work i had first nuke the appdata files related to tf2-hud-editor, then like magic everything started working.

Interesting. That might explain other issues long time users have been experiencing since the editor just keeps writing to AppData without ever clearing it. Maybe a nuke AppData option or instruction somewhere would be helpful for next release. Thanks!
